language: node_js
node_js:
  - '0.10'
  - '0.11'
before_script:
  - "./dbsetup -h127.0.0.1 -utravis"
  - make
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('admin') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - npm install -g bower grunt-cli
  - bower install 